package com.saurabh.sudoku.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// Sudoku specific colors
val SudokuBlue = Color(0xFF1976D2)
val SudokuLightBlue = Color(0xFF42A5F5)
val SudokuDarkBlue = Color(0xFF1565C0)

val CellDefault = Color(0xFFFFFFFF)
val CellSelected = Color(0xFFE3F2FD)
val CellHighlight = Color(0xFFF3E5F5)
val CellErrors = Color(0xFFFFEBEE)
val CellFixed = Color(0xFFF5F5F5)

val TextPrimary = Color(0xFF212121)
val TextSecondary = Color(0xFF757575)
val TextError = Color(0xFFD32F2F)
val TextHint = Color(0xFF9C27B0)

val ButtonPrimary = Color(0xFF1976D2)
val ButtonSecondary = Color(0xFF757575)

// Light Theme Colors
val md_theme_light_primary = Color(0xFF4359A8)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDAE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001550)
val md_theme_light_secondary = Color(0xFF595D71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDEE1F9)
val md_theme_light_onSecondaryContainer = Color(0xFF161B2C)
val md_theme_light_tertiary = Color(0xFF745470)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFED7F8)
val md_theme_light_onTertiaryContainer = Color(0xFF2B122B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE3E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_outline = Color(0xFF767680)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFFB2C5FF)
val md_theme_dark_onPrimary = Color(0xFF0F2A77)
val md_theme_dark_primaryContainer = Color(0xFF2A418F)
val md_theme_dark_onPrimaryContainer = Color(0xFFDAE1FF)
val md_theme_dark_secondary = Color(0xFFC2C5DD)
val md_theme_dark_onSecondary = Color(0xFF2B3042)
val md_theme_dark_secondaryContainer = Color(0xFF424659)
val md_theme_dark_onSecondaryContainer = Color(0xFFDEE1F9)
val md_theme_dark_tertiary = Color(0xFFE2BBDD)
val md_theme_dark_onTertiary = Color(0xFF422740)
val md_theme_dark_tertiaryContainer = Color(0xFF5B3D58)
val md_theme_dark_onTertiaryContainer = Color(0xFFFED7F8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE4E2E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE4E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF46464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C5D0)
val md_theme_dark_outline = Color(0xFF90909A)

// Sudoku Specific Colors (Now derived from theme for better blending)
val CellError = Color(0xFFF2B8B5)
val CellSelectedLight = Color(0xFFDAE1FF)
val CellSelectedDark = Color(0xFF2A418F)
val CellFixedLight = Color(0xFFF0F0F0)
val CellFixedDark = Color(0xFF2C2C30)
